GET http://localhost:5000/


###

GET http://localhost:5000/users



###

POST http://localhost:5000/api/register

     'Accept': 'application/json',
     'Content-Type': 'application/json',
{
    "name":"walid",
    "email":"vuerbvqiubviqor",
    "password":"21344738"
}